
package com.hand.cxf_server.ws.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.10
 * Thu Feb 09 16:37:30 GMT+08:00 2017
 * Generated source version: 3.1.10
 */

@XmlRootElement(name = "getOrderByIdResponse", namespace = "http://service.ws.cxf_server.hand.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getOrderByIdResponse", namespace = "http://service.ws.cxf_server.hand.com/")

public class GetOrderByIdResponse {

    @XmlElement(name = "return")
    private com.hand.cxf_server.dto.Order _return;

    public com.hand.cxf_server.dto.Order getReturn() {
        return this._return;
    }

    public void setReturn(com.hand.cxf_server.dto.Order new_return)  {
        this._return = new_return;
    }

}

