
package com.hand.cxf_server.ws.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.10
 * Thu Feb 09 16:37:30 GMT+08:00 2017
 * Generated source version: 3.1.10
 */

@XmlRootElement(name = "getOrderById", namespace = "http://service.ws.cxf_server.hand.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getOrderById", namespace = "http://service.ws.cxf_server.hand.com/")

public class GetOrderById {

    @XmlElement(name = "arg0")
    private int arg0;

    public int getArg0() {
        return this.arg0;
    }

    public void setArg0(int newArg0)  {
        this.arg0 = newArg0;
    }

}

