package com.hand.cxf_server.ws.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-02-09T17:25:14.438+08:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://service.ws.cxf_server.hand.com/", name = "OrderWS")
@XmlSeeAlso({ObjectFactory.class})
public interface OrderWS {

    @WebMethod
    @RequestWrapper(localName = "getOrderById", targetNamespace = "http://service.ws.cxf_server.hand.com/", className = "com.hand.cxf_server.ws.service.GetOrderById")
    @ResponseWrapper(localName = "getOrderByIdResponse", targetNamespace = "http://service.ws.cxf_server.hand.com/", className = "com.hand.cxf_server.ws.service.GetOrderByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.hand.cxf_server.ws.service.Order getOrderById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
