<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="OrderWS" targetNamespace="http://service.ws.cxf_server.hand.com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://service.ws.cxf_server.hand.com/">
  <wsdl:types>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
  <import namespace="http://service.ws.cxf_server.hand.com/" schemaLocation="orderws_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="getOrderById">
    <wsdl:part name="parameters" element="ns1:getOrderById">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="getOrderByIdResponse">
    <wsdl:part name="parameters" element="ns1:getOrderByIdResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="OrderWS">
    <wsdl:operation name="getOrderById">
      <wsdl:input name="getOrderById" message="ns1:getOrderById">
    </wsdl:input>
      <wsdl:output name="getOrderByIdResponse" message="ns1:getOrderByIdResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
